apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: gateway-ingress
  namespace: default
spec:
  rules:
  - host: ingress.local
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80
        path: /
      - backend:
          serviceName: api-gateway-service
          servicePort: 8080
        path: /api


