apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: backend-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8/backend.deployment.yaml
